[package]
name = "vmdl"
version = "0.1.0"
edition = "2021"
exclude = ["data"]

[dependencies]
arrayvec = "0.7.2"
thiserror = "1.0.37"
static_assertions = "1.1.0"
bitflags = "1.3.2"
itertools = "0.10.5"
tracing = "0.1.37"
bytemuck = { version = "1.12.3", features = ["derive"] }
cgmath = "0.18.0"

[dev-dependencies]
three-d = { version = "0.14.0", features = ["egui-gui"] }
miette = { version = "5.5.0", features = ["fancy"] }
criterion = "0.4.0"
iai = "0.1"
steamlocate = "1.2.1"
vbsp = { version = "0.2.0", git = "https://github.com/icewind1991/vbsp" }
vtf = { version = "0.1.5", git = "https://github.com/roman901/vtf-rs", rev = "55670df" }
vpk = { version = "0.1.4", git = "https://github.com/icewind1991/vpk-rs", branch = "perf" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[[bench]]
name = "parse"
harness = false

[[bench]]
name = "iai"
harness = false
