[package]
name = "vmdl"
version = "0.1.0"
edition = "2021"
exclude = ["data"]

[dependencies]
arrayvec = "0.7.2"
thiserror = "1.0.37"
static_assertions = "1.1.0"
bitflags = "1.3.2"
itertools = "0.12.0"
tracing = "0.1.37"
bytemuck = { version = "1.12.3", features = ["derive"] }
cgmath = "0.18.0"

[dev-dependencies]
three-d = { version = "0.14.0", features = ["egui-gui"] }
miette = { version = "5.5.0", features = ["fancy"] }
criterion = "0.4.0"
iai = "0.1"
steamlocate = "2.0.0-alpha.0"
vtf = "0.1.6"
vpk = "0.2.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
steamy-vdf = { version = "0.3.0", git = "https://github.com/icewind1991/steamy", branch = "nom7" }

[[bench]]
name = "parse"
harness = false

[[bench]]
name = "iai"
harness = false
